/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fanhua_com_umengstastics_LoadJni */

#ifndef _Included_fanhua_com_umengstastics_LoadJni
#define _Included_fanhua_com_umengstastics_LoadJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fanhua_com_umengstastics_LoadJni
 * Method:    listenUnInstall
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fanhua_com_umengstastics_LoadJni_listenUnInstall
  (JNIEnv *env, jclass job1){
    return (*env)->NewStringUTF(env,"hello jni");
  }

#ifdef __cplusplus
}
#endif
#endif